---
- hosts: all
  tasks:
  
    - name: Install the latest version of Nginx
      yum:
        name: nginx
        state: latest

    - name: Restart nginx service
      ansible.builtin.service:
        name: nginx
        state: restarted

    - name: Make sure Nginx is running
      ansible.builtin.systemd:
        state: started
        name: nginx
        enabled: yes